name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  # Disable incremental compilation. CI builds are often closer to from-scratch builds, as changes
  # are typically bigger than from a local edit-compile cycle.
  # Incremental compilation also significantly increases the amount of IO and the size of ./target
  # folder, which makes caching less effective.
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: short
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  # Cache should never take more than a few seconds to get downloaded.
  # If it does, let’s just rebuild from scratch instead of hanging "forever".
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
  # Disabling debug info so compilation is faster and ./target folder is smaller.
  CARGO_PROFILE_DEV_DEBUG: 0

jobs:
  fmt:
    name: Check code formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Check code formatting
        run: cargo fmt --all -- --check

  checks:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run tests
        run: cargo test


